version: "3.7"

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: sparkifydb
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M
